# Generated by Django 3.1.5 on 2021-01-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerAPI', '0002_customerdetail_ingredient_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderTimr',
            new_name='orderTime',
        ),
    ]
